### PR TITLE
Fix cuhornet fetch

### PR DESCRIPTION
**Pull request by leofang**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by leofang** [comment]
@kkraus14 This is a hot fix for the problem that @rlratzel identified at https://github.com/conda-forge/libcugraph-feedstock/pull/7#issuecomment-825233142.

**Review by rlratzel — APPROVED** [review]

**Comment by rlratzel** [comment]
@leofang - I hope this doesn't complicate things too much, but we're doing a [last minute fix](https://github.com/rapidsai/cugraph/pull/1557/files) for this since it breaks several other v0.19 RAPIDS builds as well. (apparently it was fixed in the prior release but our automation did not forward merge it to 0.19).

**Comment by leofang** [comment]
@rlratzel @kkraus14 RMM's 0.19.0 tag is inconsistent. On the release page the tag is https://github.com/rapidsai/rmm/commit/7065af3c3fb754d784e5f3b9751db5be49f57863, but the 0.19 branch is on https://github.com/rapidsai/rmm/commit/a6d04bf8a2f8280b67d3e365d55eb213b2fce3b1. Please advice.

**Comment by leofang** [comment]
nvm was being silly. Let me undo the patch.

**Comment by leofang** [comment]
I updated the hash to reflect the latest 0.19.0 change, which has the `GIT_SHALLOW` line fixed. I am going to merge this because I want to work on CuPy releases in the midnight and it takes about 3 hr to propagate (1.5 hr to build, 1~2 hr to update CDN). If it builds, great, if it still doesn't, we have no loss.

**Comment by leofang** [comment]
0.19.0 is uploaded!

**Pull request merged**
